### ISSUE TITLE
[REQ] Support for .webarchive files

### ISSUE THREAD

**Issue by Zabriskije** [aonez/Keka#1249]
### Describe the solution you'd like
`.webarchive` files are created when saving a web page from Safari. It would be nice to have this feature in Keka instead of relying on third-party software.

### Describe alternatives you've considered
[WebArchive Extractor](https://github.com/robrohan/WebArchiveExtractor)

**Comment by aonez** [comment]
Thanks for the feedback! This will be pretty easy to implement. I've checked the `webarchive` and it's basically a `plist`.

**Comment by Zabriskije** [comment]
Awesome to hear!

OT: if you need help with #1074 let me know 😉

**Comment by aonez** [comment]
This one should do it: [Keka-v1.2.62.r5165](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.62.r5165.7z)

Let me know if it fails on some webpages. I found it to be very unstable on 10.12 or earlier, since the WebArchive API crashes with many websites. But 10.13 and up it's pretty stable.

**Comment by aonez** [comment]
Note the default action for Keka is to compress WebArchive since it's a non compressed format. So you should use the extract action (window, contextual menu...) to extract them.
