### ISSUE TITLE
[BUG] eorror code 2 

### ISSUE THREAD

**Issue by lkmin9747** [aonez/Keka#1274]
### Configuration
- Keka version: [e.g. 1.1.24 (3421)]
- macOS version: [e.g. 10.14.6 (18G2022)]

### Describe the bug
Attach a log file reproducing the issue: https://github.com/aonez/Keka/wiki/Report-an-issue

### To Reproduce
<img width="395" alt="스크린샷 2023-06-21 오후 3 03 58" src="https://github.com/aonez/Keka/assets/137260936/57c44efc-3994-49cc-a632-aa1acf526d7b">

2. Click on '...'
3. Scroll down to '...'

**Comment by gingerbeardman** [comment]
Try this

https://github.com/aonez/Keka/wiki/Error-accessing-the-binary

**Comment by aonez** [comment]
@lkmin9747 those part numbering seem wrong. Do you have all parts for `천호 원본1.2jp.001`, being `천호 원본1.2jp.002`, `천호 원본1.2jp.003`...

Also try updating your Keka version since I see the rounded icon.

@gingerbeardman the error for the binary should state "Binary ... is not accessible". Although is possible the binary is being forcibly quit by macOS during the operation in which case can be an error code 2.
