### ISSUE TITLE
[BUG] .webarchive extraction misses index file

### ISSUE THREAD

**Issue by Zabriskije** [aonez/Keka#1287]
### Configuration
- Keka version: 1.3.2 (5208)
- macOS version: 13.4.1 (22F82)

### Describe the bug
.webarchive extraction doesn't include an index file

### To Reproduce
1. Save a web page (<kbd>⌘</kbd>+<kbd>S</kbd>)
2. Extract the .webarchive with Keka

### Expected behavior
.webarchive extraction should include an index file

### Additional context
I don't remember if this was also present in v1.2.62.r5165

**Comment by aonez** [comment]
Sadly I've removed the dev builds but I've made no changes to the parser since its introduction in #1249.

Are you sure the page should include that index file? For example saving this issue as a webarchive has the html file like this:

<img width="372" alt="Screenshot 2023-07-08 at 12 56 54" src="https://github.com/aonez/Keka/assets/480163/5d1ed1d7-6082-4c67-b77e-ccd9e6f568a2">

**Comment by aonez** [comment]
I see what might be happening. Checked with a [random web](http://www.dpgraph.com) and indeed it has no html at all. Seems I've missed somehow to parse the `WebMainResource` if it has no name defined.

**Comment by aonez** [comment]
The index was being parsed but written outside the extraction folder, in the temporary package of Keka that gets removed after the extraction.

Fixed in this build: [Keka-v1.3.3.r5212](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.3.3.r5212.7z)

Thanks for the tip @Zabriskije!

**Comment by Zabriskije** [comment]
v1.3.3.r5212 did the job. Thank you for the fast fix :)

**Comment by aonez** [comment]
This is finally published in 1.3.3 😊
