### ISSUE TITLE
[BUG] Keka fails to extract apps when resource forks are excluded

### ISSUE THREAD

**Issue by eproxus** [aonez/Keka#1310]
### Configuration
- Keka version: 1.3.2 (5208)
- macOS version: 13.5 (22G74)

### Describe the bug
Keka corrupts the content of the following file while extracting, when excluding resource forks: https://download.sublimetext.com/sublime_merge_build_2090_mac.zip (MD5 checksum `a7ff9085547134ae2613485547c11a4f`)

### To Reproduce
1. Download https://download.sublimetext.com/sublime_merge_build_2090_mac.zip
2. Enable the _Extraction_ setting _Exclude Mac resource forks (eg: .DS_Store)_ 
3. Extract the file with Keka
4. See error when trying to open the application

### Expected behavior
Zipped applications are extracted correctly.

### Screenshots
<img width="372" alt="Screenshot 2023-08-21 at 09 39 01" src="https://github.com/aonez/Keka/assets/112878/e9b967e5-7a6e-40c1-a10b-865b043d19d7">

**Comment by aonez** [comment]
Hi @eproxus,

That app package contains metadata for some files. So Keka does not fail to extract, but if you exclude Mac forks (metadata) in the extraction process the application fails to open because it's missing some metadata and it's signature can't be verified properly. I recommend that you disable that option in Preferences - Extraction (you're working on macOS), and only have it enabled for compression (sharing with Windows, Linux).

You should report this issue to the developers of that application so they remove all unnecessary metadata from their app before signing and packaging it. It's a bad idea to have metadata on an app package and most probably they did not know there was some.
