### ISSUE TITLE
Stalls on 2/150 files

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#133]
- zip files set to open in keka
- select 150 zips in Finder
- open

![screen shot 2018-01-29 at 16 11 51](https://user-images.githubusercontent.com/49612/35520794-f7ea0fce-050f-11e8-9f0a-e98ee09e7b34.png)

**Comment by aonez** [comment]
Can't reproduce this one. Did you reproduced it?

**Comment by gingerbeardman** [comment]
It's an retro game ROM, very small. Less than 1MB. I'll try to reproduce.

**Comment by aonez** [comment]
So I did found the bug. Any extraction using the new queue system (10+ compressed files) will internally crash on the second file in the queue, and the operation will hang forever.

It is only affecting beta versions since beta 3, I first tested it in the stable release, that's why I did not get the crash. Already fixed for the next release.

Thanks for the tip @gingerbeardman!

**Comment by gingerbeardman** [comment]
Sorry I did not specify I was using the beta

**Comment by aonez** [comment]
Fixed on beta 6 😊
