### ISSUE TITLE
confusing advanced window toolbar

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#142]
I appreciate you're trying something different. 

But this is confusing. Particularly the empty dropdown.

![screen shot 2018-03-08 at 11 24 18](https://user-images.githubusercontent.com/49612/37152183-5b6407de-22d0-11e8-8fe7-ccb65f9dc314.png)

**Comment by anthony-wang** [comment]
+1. I usually like to click around in new apps/versions to discover what's changed, but other users might not and might not notice this.

**Comment by MaxPower85** [comment]
I agree... new users should be able to instantly understand which icon means what when they just look at the screen without having to click around too much or to memorize which icon color represents which format... I think that all icons should show the text of what they represent if it's not clear from the icon's design what it means (looking at a red icon wouldn't make someone instantly think of ZIP format if he didn't see that icon before) and it should be clear which format is currently selected without hiding the text of other icons.

I think that it would be best if there were tabs for TAR, ZIP, 7-ZIP, DMG and ISO and if the drop-down menu was not there in the toolbar... the drop-down menu for other formats could be moved under TAR's settings (when you click on TAR's tab), since you are using TAR anyway if you are archiving files to GZIP or BZIP2 or XZ, so it makes perfect sense for that to be under TAR as "Compression format" (and you can include "None" in the drop-down menu if someone doesn't want to compress TAR... it would also be useful to include 7-ZIP and ZIP for compressing TAR if someone wants that for some reason... maybe if someone wants to use TAR to preserve resource forks, but he also wants to compress it with 7-ZIP if he wants to use encryption and he wants Windows users to be able to open it easily).

BTW... maybe you could also add some OpenSSL encryption options to TAR's tab... it's not uncommon for *nix users to encrypt TAR archives by using a pipe to send the output from TAR to OpenSSL... and OpenSSL is included with macOS natively, so it's just a simple command to make, for example, a TAR archive with XZ compression and to send the output to OpenSSL to write an encrypted file to disk.

**Comment by gingerbeardman** [comment]
In an earlier beta it used to be different. 

below is an old screenshot of the dropdown taken from here: https://github.com/aonez/Keka/issues/129

![https://user-images.githubusercontent.com/49612/35385575-a3b85412-01c0-11e8-9592-b0db0c21ac21.png](https://user-images.githubusercontent.com/49612/35385575-a3b85412-01c0-11e8-9592-b0db0c21ac21.png)

**Comment by aonez** [comment]
The idea of the dropdown is to have all the formats that are not in a unique toolbar button. So for example if you customize the toolbar and add the RAR button to it, it will not appear on the dropdown.

But fro what I get from your comments, maybe will be better to only have the dropdown list with all the formats and get rid of the "shortcut" toolbar buttons for specific formats.

**Comment by MaxPower85** [comment]
@aonez 
You could allow shortcut buttons if you want, but just make it obvious what is what without making new users click around the app to see what will happen... for example, always show the currently selected format in the drop-down menu (to make it clear to what format is Keka going to compress if they drag&drop something) and if a shortcut is clicked change the selected format in the drop-down menu to that automatically (you don't have to change the icon for the shortcut)... don't change the drop-down menu to something blank and don't hide the text from the shortcuts (you could just write "zip", "tar", "xz" on the icons in a small font and not show additional text next to the icon, if you want to save space... I'm not sure how many Mac users are using Retina Macs right now, but I'm guessing that most would be able to see the small font clearly... and for those without Retina Macs, maybe there could be a tooltip)... but in that case, don't allow someone to remove the drop down menu and to just have button-like shortcuts if the drop-down menu was needed to show which format is currently selected (if someone wanted to remove the drop-down menu, then just change the shortcuts to that old "tab-style" shortcuts), so someone wouldn't drag-out the drop-down menu and then complained that interface is confusing if he then didn't know what was selected.

You could also leave out the shortcuts... but with that small drop-down menu alone, the toolbar looks kind of empty... maybe if you also added a drop down for compression level next to it or a slider... and if you are looking for ideas to redesign the interface, maybe a small locked/unlocked padlock button in the toolbar could be added that would show the password fields (and if the password was entered, the padlock could change to locked to indicate that)... and a cog button to reveal other settings (maybe "split" could go under "other settings" in that case, or maybe it could also have a small button... maybe "split" could be represented by a file icon that looks diagonally cut in half)... with all those options in the toolbar, it could really be called "unified toolbar"... and the rest of the window could just say "Drop files here" then (and it could change to "password settings" or "other settings" depending from which button was pressed)... but leave the option in Keka's preferences for the "old style" Keka interface, if someone likes it better.

Maybe having the main part of the window say "Drop files here" when Keka is opened while having the options in the toolbar would be good... to make it clear for new users that they need to drag&drop files... some new users don't seem very accustomed to expect drag&drop (maybe they are switching from a platform where drag&drop isn't used as much as it is on Mac).

**Comment by gingerbeardman** [comment]
@aonez I think that approach is better. I still think that the format names shouldn't be mixed case.

**Comment by aonez** [comment]
I'll remove the buttons for next revision. Only the dropdown will be used when the unified toolbar is used.

**Comment by MaxPower85** [comment]
You could add just the shortcut icons with text on them, without them being inside buttons... and make clicking a shortcut change the selected format in the drop-down menu.

This looks kind of really empty: 
![screen shot 2018-03-19 at 10 52 53 pm](https://user-images.githubusercontent.com/37249460/37625298-a89adff6-2bcb-11e8-8aea-6cae98992a08.jpg)

But you could fit icons with readable text if you don't put them inside of buttons... here's one icon opened in Preview next to Keka's window... maybe just make the text on the shortcut icons somewhat larger
![screen shot 2018-03-19 at 10 55 33 pm](https://user-images.githubusercontent.com/37249460/37625342-d1173358-2bcb-11e8-9e1c-7cac07dc38ac.jpg)

Also... in "tabbed" mode, make clicking a tab show that format in the drop-down menu, instead of having that empty drop-down there...
![screen shot 2018-03-19 at 9 52 20 pm](https://user-images.githubusercontent.com/37249460/37625426-2d60c818-2bcc-11e8-9579-67b20ac2ad63.jpg)

And maybe for the tabbed view this would be a better default layout... 
![screen shot 2018-03-19 at 11 00 15 pm](https://user-images.githubusercontent.com/37249460/37625465-5314ee5e-2bcc-11e8-882d-cdba1340d232.jpg)

But if someone chooses to add the drop-down menu there, make it always show the current format.

Also... if someone choose to only show icons without text, there should be some way to distinguish between DMG and ISO, even if someone remembers all the colors... it would be good if there was some text on those icons, at least in that mode because this could confuse users
![screen shot 2018-03-19 at 11 01 23 pm](https://user-images.githubusercontent.com/37249460/37625539-a0cb3a40-2bcc-11e8-9d98-e83c504da2e3.jpg)

BTW... you could add the View menu in the Menu bar to choose between the tabbed or compact mode and between smaller or bigger icons in tabbed mode and the option to customize the toolbar could be there too... options like those are usually in the View menu for other apps.

**Comment by gingerbeardman** [comment]
Interestingly this is what the non-beta (the latest version of which was released today) looks like:

![screen shot 2018-03-19 at 23 11 53](https://user-images.githubusercontent.com/49612/37627148-03eea654-2bcb-11e8-9d00-154d11350b4d.png)

**Comment by gingerbeardman** [comment]
Something like this would work for me? Boring/obvious/standard, I know.

![keka](https://user-images.githubusercontent.com/49612/37627447-513bfd16-2bcc-11e8-9138-db01bda82222.png)

**Comment by aonez** [comment]
> Boring/obvious/standard, I know.

@gingerbeardman legacy... Keka 0.1 frist public alpha:
![screen shot 2018-03-21 at 11 41 30](https://user-images.githubusercontent.com/480163/37705612-e587ebf2-2cfc-11e8-948f-60f9d538552a.png)

@MaxPower85 the unified toolbar is the way to go and will be the default. I'm keeping the older toolbar for compatibility with OS X 10.9. The older toolbar items don't feel good in the unified toolbar. I'm adding two new formats (xz and lzip) in this beta but will add more in the future, so the dropdown was the best way to have them all on the toolbar, no matter if they are 9 or 20, and the most commonly used in a separate button (customizable, the most common for me may be not for you).

I still think buttons and dropdown will work, just need to improve the buttons behaviour, add static text to them and decide how to show the dropdown when it's not used.

**Comment by aonez** [comment]
By the way @gingerbeardman, you can shot window screenshots (with shadow) using:
- cmd ⌘ + shift ⇧ + 4 + spacebar

In case you didn't knew it. This saved me a lot of time of white background and image edition.

**Comment by gingerbeardman** [comment]
Yes, I use that useful shortcut, I just made a quick and sloppy edit on the image 😂
