### ISSUE TITLE
xyz.app is damaged and can not be opened

### ISSUE THREAD

**Issue by TommySlokky** [aonez/Keka#1450]
### Configuration
- Keka version: [e.g. 1.3.8 (5320)]
- macOS version: [e.g. 11.7.10

I have a codesigned app. I zip it using Info-Zip commandline.
If I unzip using same commandline OR using builtin macos "Archive Utility" my app works.

But if Keka unzips it, then opening the app gives error:

"xyz.app is damaged and can't be opended. You should move it to Bin. 

Keka created this file on an unknown date."

Is there any way to solve this from my side? Or is this a Keka bug? Let me know if you need more information.

**Comment by aonez** [comment]
Hi @TommySlokky, is it possible that I get a sample to test? You can send it to info@keka.io

I had similar issues where the problem was a file in the app bundle with some special characters that can get extracted with a similar but not equal name and thus the signature of the app fails to be verified.

**Comment by aonez** [comment]
@TommySlokky I'm testing the file now.

> If I unzip using same commandline OR using builtin macos "Archive Utility" my app works.

I can't reproduce what you said here. No matter how I extract the file it always fails to execute properly. The compression is badly made.

```sh
/Users/aone/Downloads/mac-techseo360-files/TechSEO360.app: a sealed resource is missing or invalid
file modified: /Users/aone/Downloads/mac-techseo360-files/TechSEO360.app/Contents/Resources/trans/en-us/UTF8_shared.ini
file modified: /Users/aone/Downloads/mac-techseo360-files/TechSEO360.app/Contents/Resources/trans/en-us/UTF8_general.ini
file modified: /Users/aone/Downloads/mac-techseo360-files/TechSEO360.app/Contents/Resources/trans/en-us/UTF8_program.ini
```

The issue is with those file. Probably an encoding issue with the file or something similar. I suggest you manually recreate those files and compile the app again.

**Comment by TommySlokky** [comment]
As noted in the email, when I too download it also always fails no matter what tool which was why I was somewhat resignated in the email and wrote I would email again when I had figured that part out. 

I **very much appreciate** your comments and help. The odd thing is those files are only changed infrequently of course except the moving them from my Windows machine to Mac machine which is done by a script. (TechSEO360 uses Delphi for Windows and Lazarus for MacOS.) And they are never modified during the build process. (i.e. codesign, notarize, stable, zip.)

But thanks to you your help I am hopefully a step closer. Thank you very much. I will return over email if I come close to the reason.
