### ISSUE TITLE
[BUG] If a folder which is to be extracted already exists, the number appended to the folder name starts at 3, not 2

### ISSUE THREAD

**Issue by OnesuchDev** [aonez/Keka#1537]
### Configuration
- Keka version: 1.4.4
- macOS version: 14.7 (23H124)

### Describe the bug
If a folder which is to be extracted already exists, the number appended to the folder name starts at 3, not 2.
This was working correctly quite a while ago, but I'm not sure exactly what version of Keka broke it.

### To Reproduce
1. Extract an archive which creates a folder, say, "folder"
2. Extract the same archive again to the same folder
3. Observe that the resulting folder is named "folder 3" instead of "folder 2"

### Expected behavior
The resulting folder is named "folder 2".

### Additional context
Keka has Full Disk Access permissions.

**Comment by aonez** [comment]
Thanks @OnesuchDev. Checked this out and turns out it's like this since v1.3.0 (06/2023), worked properly in v1.2.61. The bug was introduced since there was a redesign of the naming code in this v1.3.0 change:
- Enhanced extraction naming with multiple extensions

Sadly just released v1.4.5 so this fix will be available in a few weeks since it is not critical.

But already published a fixed build that you can use as your daily driver:
https://d.keka.io/test/Keka-v1.4.6.r5512

**Comment by aonez** [comment]
v1.4.7 is public now. Thanks again @OnesuchDev.
