### ISSUE TITLE
Choosing default action for specified file formats

### ISSUE THREAD

**Issue by wangweixuan** [aonez/Keka#170]
There are some file formats that are extended from zip. For example, [.jar, .apk](https://en.wikipedia.org/wiki/JAR_(file_format)), and [.appx](https://en.wikipedia.org/wiki/Open_Packaging_Conventions).
I have set `Perform automatic action` in the preferences. Now when these files are passed to Keka, Keka automatically compresses them, but I want it to extract them. So please consider a preference to let the users decide which action should be applied when dealing with specified file formats.

**Comment by gingerbeardman** [comment]
BetterZip lets you hold alt to switch the behaviour from compress to extract. I think it could be done better, as it always takes me a second launch to get the behaviour I want. 

Maybe two modifier keys? One to force expand, one to force compress?

**Comment by aonez** [comment]
@wangweixuan I might consider set the default behaviour to extract them, since they are ZIP files. And eventually adding the customisation will come, adding this to #59.

@gingerbeardman I like the idea. Maybe `option` to compress, as in Finder to copy, and `command` or `option` + `command` to uncompress.

Also don't forget that you can always [do the alternate action](Extracting-with-Keka#how-to-extract-supported-files) to the default, using the bottom of the drop window:

![extract-alternate](https://user-images.githubusercontent.com/480163/38412120-ec65defa-3988-11e8-81a4-6cdad5d22793.gif)

**Comment by gingerbeardman** [comment]
I have never used the drop window 😳

**Comment by aonez** [comment]
> I have never used the drop window 😳

I must do something with that... Lots of users don't know this functionality... #41

**Comment by aonez** [comment]
Added `JAR`, `APK` and `APPX` to the extraction list for next beta.

The customisation of extensions will follow here #59.

**Comment by aonez** [comment]
[Beta 10](https://github.com/aonez/Keka/releases/tag/v1.1.0-beta.10) ready, extracting this formats as default.

**Comment by ydq** [comment]
@aonez  I think the default action of the `.war` files ( java web package format )  should be the same as the `.jar` file. Please fix it. Thanks!

**Comment by aonez** [comment]
Thanks for the tip @ydq! Added for the next revision 👍
