### ISSUE TITLE
decompression reveals a file name other than the zipped one

### ISSUE THREAD

**Issue by seitsme** [aonez/Keka#179]
hi there,

i zipped a file with password protection.  ZIP format.
it contained 3 files - filenames.

the compressor never asks for a name for final gile if i select ie 3 files and drag them on window.
Would be nice to ask for filename.

When i double clicked on my mac - high sierra to test if file opens and asks for pwd,
the default decompressor is apple archive utility.

The archive utility starts then opens a window asking for pwd.
on the window there is a message saying...
PLEASE ENTER THE PASSWORD FOR and in brackets displays one of my 3 zipped filenames
including their extension, revealing a sensitive document filename, compressed in the archive....

so would be nice to fix this issue or make the program replace the filename with the filename stored on disk. maybe this is also related to the problem of manual selecting a batch of files, as it does not ask for a final filename of compressed form and by default the archive utility gets access to the filename list ...

thanks

**Comment by aonez** [comment]
The Zip format does not encrypt the filenames, that's why you can list them. If you want to also encrypt the filenames, use 7z format instead with "Encrypt filenames" option activated.

You can also choose a custom name or name and destination, take a look at the compression Keka preferences. Set there your preferred options.

![screen shot 2018-05-03 at 12 46 37](https://user-images.githubusercontent.com/480163/39572641-49b801e4-4ed0-11e8-973e-c50f42a4a6f3.png)
