### ISSUE TITLE
1.1.0rc1 crashes at startup [OS X 10.8]

### ISSUE THREAD

**Issue by jhzzzzz** [aonez/Keka#182]
As the title states, 1.1.0rc1 crashes at launch.
1.1.0ß5 works perfectly on the same machine.

In the console :
03/05/18 22:20:50,289 ReportCrash[8474]: Attempting to read data: Called memoryAtAddress: 0xc0003a7373616c43, which is in an unmappable portion of [0x0 -> 0xffffffffffffffff] in PID# 8478.

Hope it can help figure out what's happening.

**Comment by aonez** [comment]
[Beta 6](https://github.com/aonez/Keka/releases/tag/v1.1.0-beta.6) is the last one compatible with Mac OS X 10.8. [Beta 7](https://github.com/aonez/Keka/releases/tag/v1.1.0-beta.7) and newer need 10.9 or newer. Sorry about that.

Just out of curiosity, where you still use 10.8?

**Comment by jhzzzzz** [comment]
I'm still using 10.8 due to old (abandoned) applications that don't work on following releases.
But it's getting harder as more and more applications require 10.9 or newer.
Just out of curiosity, what is (are) the technical factor(s) that render Beta7+ incompatible with 10.8?
Is it just a choice (10.8 unchecked in a config file) or is there a real justification?

Thanks for your reply anyway.

**Comment by MaxPower85** [comment]
Eventually, all of us will probably have to update because of something... especially since new Macs usually don't support using a version of OS X/macOS that's much older than the Mac you bough...

So if some app became abandonware... it would be a good idea to start looking for alternatives and if some other app doesn't have all features you liked in some old app, maybe you should send feature requests to it's developers... and maybe they'll add it eventually if you keep asking them and there are good reasons to add some feature...

Just to stay prepared for switching to a new Mac eventually... so you wouldn't put yourself in a situation where you have various apps that you are used to using in your daily workflow, but you can't use them on your new Mac.

And if you only need some really old app sometimes and you can't find alternatives right away, consider using it in a VM... you could also consider using a Windows version of some app in a VM, since Windows in a VM seems to work much better than OS X / macOS in a VM (with hardware acceleration, Retina support and things like that).

**Comment by jhzzzzz** [comment]
Thanks for all these tips, but you didn't tell the reason why Keka 1.1.0 Beta 7+ is incompatible with OS X 10.8. Is it a technical limitation or a choice?
If it is definitive, it would be a good idea to :
- tell it on the site ;
- compile it so that at launch the OS informs the user it doesn't meet the requirements rather than let the app crash.

**Comment by MaxPower85** [comment]
I don't know... you'll have to wait for aonez for that info.

But OS X should inform the user if some app requires a minimum system version higher than what he's using and not allow the app to run on earlier versions, if the minimum system version was listed under "LSMinimumSystemVersion".

So if you are getting a crash instead of OS X notifying you that you can't run it, that's still a bug and should be fixed.

I checked the Info.plist file now...

I see there is this part...
```
	<key>Minimum system version</key>
	<string>10.9</string>
```
It should say `LSMinimumSystemVersion` instead of `Minimum system version`.


BTW... did you try to edit Info.plist to see would it maybe work on 10.8?

You can use `plutil -convert xml1 ` to convert it to a format that you can edit in a text editor... and just drag & drop the Info.plist after that before pressing Return/Enter

Find the part I mentioned and see if changing it to this would maybe work for you...

```
	<key>LSMinimumSystemVersion</key>
	<string>10.8</string>
```

When you are done editing and you save the file, convert it back to binary format with this:

`plutil -convert binary1 ` ... and drag&drop the Info.plist file before pressing Return/Enter

**Comment by aonez** [comment]
@jhzzzzz the auto-layout used on all the GUI from beta 7 requires 10.9. I really would love to support older versions, but some times it’s not possible. Was hard to ditch 10.7, since it’s the latest compatible OS for some Macs.

As @MaxPower85 pointed the app already is informing the minimum supported OS. I’ll double check that, you shouldn’t be able to run that version, indeed.

**Comment by aonez** [comment]
Checked, fixed the `LSMinimumSystemVersion` key. This must have been wrong forever! Thanks @MaxPower85 and @jhzzzzz.
