### ISSUE TITLE
[REQ] archive takes name from containing folder

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#188]
Rather than "Compressed file.7z"

it would be nicer if the archive took the name of the containing folder.
7z on Windows does this. Very handy.

Keka already takes name of file if compressing a single file

**Comment by aonez** [comment]
I'm not sure about that. For me it's confusing to compress a bunch of files in the Desktop and have a file named Desktop.7z...

**Comment by sevdestruct** [comment]
Since my request got related to this. I thought I'd cast a comment into this for discussion.

What is the use case of this? Seems to be an unnecessary optional setting with little to gain, but I mean no disrespect, just curious about the use case if you can explain why it's handy.

Wouldn't `Desktop.7z`, `Desktop 2.7z` … `Documents.7z`, `Documents 2.7z` basically the same as `Compressed file 2.7z` or Apple's `Archive.zip` and `Archive 2.zip` etc… as it gets created in that containing folder giving it context by position… Considering that folders dropped onto Keka already compress into this type of naming, what exactly is the benefit?

**Comment by gingerbeardman** [comment]
It's something I use frequently and miss in Keka, not something I've just thought up that might be nice 😉

The use case is when I want to archive some files (but not the whole folder) and I do not want the folder name stored in the archive. Currently I have to do a manual rename afterwards. 

At the very least "Desktop.zip" is descriptive of where the contents came from. "Compressed file.zip" or "Archive.zip" could come from anywhere, and if I have multiple of them then it's an inconvenience.

**Comment by sevdestruct** [comment]
Fair enough…I guess I can think of a couple more instances where that might be useful as an optional checkbox, after pondering about it a bit.

What are your thoughts on the other suggestion I made above, might be a better default than `Compressed file #.7z` in general, instead of an alternate to the request here. Perhaps I should move that to it's own request ticket…

**Comment by gingerbeardman** [comment]
Your suggestion is interesting, I think it would be useful sometimes but how much would need me to try it out for a while.

Here's me using 7z on Windows just now:

![screen shot 2018-07-09 at 01 09 39](https://user-images.githubusercontent.com/49612/42425405-f7f71114-8314-11e8-884b-4d2d8da64edf.png)

**Comment by aonez** [comment]
@gingerbeardman I also use 7-Zip in Windows environments and this is the default behaviour. Being so simple to implementation, and it benefiting some users, I don't see why not adding that one.

**Comment by aonez** [comment]
A check will go below `Same as original file`, something like `Name as containing folder if multiple files`

![screen shot 2018-07-09 at 14 08 13](https://user-images.githubusercontent.com/480163/42449600-92f405f2-8381-11e8-8ca3-ab1073b7fd13.png)

**Comment by Askhento** [comment]
> A check will go below `Same as original file`, something like `Name as containing folder if multiple files`
> 
> ![screen shot 2018-07-09 at 14 08 13](https://user-images.githubusercontent.com/480163/42449600-92f405f2-8381-11e8-8ca3-ab1073b7fd13.png)

Hello, I've opened a duplicate. Sorry for that. 
Where can I find this option you mentioned in a screenshot? Settings?

**Comment by aonez** [comment]
> Where can I find this option you mentioned in a screenshot? Settings?

Will be there, but it's not yet implemented.

**Comment by aonez** [comment]
> Would inference of the type of things archived or simply the leading file or folder give more context…

@sevdestruct sorry for the late response. That has been asked again in #501. This is hard to accomplish in a way that everyone recognizes the file and is useful and depending on the complexity may also have a performance impact.

Right now I'm not considering that option since counting the files might be 👍🏼 for 10 but not for 10.000, imagine detecting a pattern or something else. The name selection should be very fast.

**Comment by aonez** [comment]
@gingerbeardman & @Askhento take a look at the latest dev build:
https://github.com/aonez/Keka/releases/tag/v1.2.0-dev.3742

There you have this option (enabled by default in new installations).

![Screen Shot 2019-12-20 at 13 42 54](https://user-images.githubusercontent.com/480163/71255614-a1e79d00-232e-11ea-9c41-f50e3ef63122.png)

**Comment by Askhento** [comment]
> @gingerbeardman & @Askhento take a look at the latest dev build:
> https://github.com/aonez/Keka/releases/tag/v1.2.0-dev.3742
> 
> There you have this option (enabled by default in new installations).
> 
> ![Screen Shot 2019-12-20 at 13 42 54](https://user-images.githubusercontent.com/480163/71255614-a1e79d00-232e-11ea-9c41-f50e3ef63122.png)

Wow you made it really fast! 
I also made an automator with bash script :D 

Ok have installed it by dragging into Applications and left both versions, but new one looks the same.

![image](https://user-images.githubusercontent.com/34323808/71256744-c0579380-2342-11ea-8c85-b80bd34c19fd.png)

Where all the setting?

**Comment by aonez** [comment]
Look in the Keka Preferences - Compression

**Comment by Askhento** [comment]
Yes! Works as expected. 
Is it okay to ask about implementation of this feature? Just to compare the solutions...

**Comment by sevdestruct** [comment]
> > Would inference of the type of things archived or simply the leading file or folder give more context…
> 
> @sevdestruct sorry for the late response. That has been asked again in #501. This is hard to accomplish in a way that everyone recognizes the file and is useful and depending on the complexity may also have a performance impact.
> 
> Right now I'm not considering that option since counting the files might be 👍🏼 for 10 but not for 10.000, imagine detecting a pattern or something else. The name selection should be very fast.

Hey @aonez It's quite alright. I've been so busy this past year -  happy to see some movement on conversations here. I'm trying to catch up on side projects and contributions here on github for the new year.
