### ISSUE TITLE
Support extracting rar multi-part archives beyond .r99

### ISSUE THREAD

**Issue by kennethlynne** [aonez/Keka#350]
I have multi-part rar archives that consist of rar files named like this:

a.rar
a.r00
a.r01
....
a.r99
a.s00
...
a.s99
a.t00
...
a.t99

but keka is only set as the default app for the a.r** files

**Comment by kennethlynne** [comment]
![image](https://user-images.githubusercontent.com/390817/50904217-0eb89e80-1420-11e9-856d-f7546c04a18c.png)

**Comment by aonez** [comment]
Thanks for the feedback @kennethlynne!

The problem here is that the list of registered extensions will be huge, since legacy RAR uses multiple characters beyond **r**, not just **s** and **t**. Those files are recognized, but for better performance only the first 99 starting with an **r** are set.

Note that since the introduction of RAR version 5, introduced in 2013, all parted files have a **.rar** extension, like _file.part001.rar_.

**Comment by kennethlynne** [comment]
Alright makes sense. So I should use some batch renaming tool to rename them instead?

**Comment by aonez** [comment]
> So I should use some batch renaming tool to rename them instead?

No!

About the screenshot, seems you had a problem with an extraction. You can enable the [console verbose](https://github.com/aonez/Keka/wiki/Console-verbose) to see more information on the Console.app. Just close Keka, execute this line in the Terminal.app and try the extraction again:

```sh
defaults write com.aone.keka DevLog -bool true; defaults write com.aone.keka DevLogReader -bool true;
```

Disable this verbosity once you get the error message, since it has a performance impact to have this enabled. To disable simply:

```sh
defaults write com.aone.keka DevLog -bool false; defaults write com.aone.keka DevLogReader -bool false;
```
