### ISSUE TITLE
Context Menu Services Not Available

### ISSUE THREAD

**Issue by Ballou** [aonez/Keka#391]
Hi. Thanks for the software! I am running Keka Version 1.1.14 (3291) on OS X El Cap 10.11.6 (15G22010). I do not have Keka context menu options available, nor are they listed in file services. I've tried to find them in System Prefs>Keyboard>Shortcuts>Services>Files and Folders, but they are not listed as available there either. Is it because I am running an older OS? Do I manually need to create Automator Services? I'd like to be able to create encrypted Zip files from the context menu. Thanks again!

**Comment by aonez** [comment]
@Ballou the bundled services are compatible at least since 10.9, and they usually activate by default. Are you using any language other than the English in Keka?

![Screen Shot 2019-04-04 at 08 32 50](https://user-images.githubusercontent.com/480163/55534289-46985080-56b4-11e9-95fb-ce2cbbdb1bc2.png)
![Screen Shot 2019-04-04 at 08 32 15](https://user-images.githubusercontent.com/480163/55534291-48621400-56b4-11e9-9d88-6c916882bad8.png)

**Comment by Ballou** [comment]
A simple reboot of my machine resolved the issue. Apologies, I should have tried the obvious. Appreciate the reply!!
