### ISSUE TITLE
Strange nested double extraction of this LZH

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#395]
Similar to #390?

[font_all.lzh.zip](https://github.com/aonez/Keka/files/3054136/font_all.lzh.zip)

from: http://rutosa.com/pp/font_all.lzh

I get an error

![Screen Shot 2019-04-08 at 12 59 06](https://user-images.githubusercontent.com/49612/55722443-3b1f8f00-59fe-11e9-8d7d-08de5d302c9d.png)

and this output 

![Screen Shot 2019-04-08 at 13 04 31](https://user-images.githubusercontent.com/49612/55722715-ef211a00-59fe-11e9-9ec2-b722a1c6361a.png)

...seems to go into recursive/infinite loop?

--- 

Archiver.app extracts it without error.

![Screen Shot 2019-04-08 at 13 04 52](https://user-images.githubusercontent.com/49612/55722722-f1837400-59fe-11e9-8a5a-92f460187214.png)

**Comment by aonez** [comment]
Hi @gingerbeardman!

The duplication most probably was because you run the operation twice, and one of the times inside the previous extraction? I did not got that result.

As for the error, the file seems to be corrupt. The file **s8.bdf** is only partially extracted. The original file was 878293 bytes but only 786432 can be extracted. I'm not sure why the Archiver.app does not show the error, but it also only partially extracts that file.

This is the output generated with **lha-1.14i-ac20040929**:

```sh
PAWFF.LOG	- Melted   :  o
s8/s8hn.bdf	- Melted   :  oooo
s8/S8.FNT	- Melted   :  oooooooo
s8/s8.ttf	- Melted   :  ooooooooooooooooooooooooooooooooooooo
s8/s8.txt	- Melted   :  o
s8/s8_jos4.prc	- Melted   :  ooooooo
s8/s8.bdf	- Melting  :  ooooooooooooooooooooooooooooooooooooLHa: Error: Bad table (case a)
LHa: Removing: s8/s8.bdf
```

Maybe you can try downloading that file again, in case it was downloaded.

**Comment by gingerbeardman** [comment]
No, I do not run it twice.

Video: https://0x0.st/zZ4V.mov

**Comment by gingerbeardman** [comment]
Also get bad table with this one, which results in two files

[dasaji_w-1.lzh.zip](https://github.com/aonez/Keka/files/3055975/dasaji_w-1.lzh.zip)

If they are truly bad, that is a shame. I will investigate.

**Comment by aonez** [comment]
Just reproduced the double compression, reopening this one. Thanks @gingerbeardman!

**Comment by gingerbeardman** [comment]
What was the problem?

**Comment by aonez** [comment]
> What was the problem?

Since 1.1.14 if UNAR fails P7ZIP is used instead. In this case UNAR fails but extracts some files then P7ZIP is used and hence the duplication. Just removing that first failed extraction.

**Comment by aonez** [comment]
It's curious how some apps I've tried with this fonts file just ignore the existence of the damaged **s8.bdf** file.

**Comment by gingerbeardman** [comment]
>It's curious how some apps I've tried with this fonts file just ignore the existence of the damaged **s8.bdf** file.

@aonez indeed it is
