### ISSUE TITLE
Preferences overwritten on first launch

### ISSUE THREAD

**Issue by built2order** [aonez/Keka#439]
**Use Case**
As an administrator, I want a user to install the application with default configuration.

**Expected Behaviour**
User installs application (including configuration) and configuration should be read and set during first launch.

**Actual Behaviour**
User installs application (including configuration) however preferences file is reverted to default during first launch.

**Reproduction**
Assuming Keka.app is available in /Applications folder

1. open the Terminal and type this command:
`defaults delete com.aone.keka`
2. open the Terminal and type this command:
`defaults write com.aone.keka ZipUsingAES -bool TRUE`
3. open Keka and navigate to Preferences. Note that the value is not set.
4. To confirm, open the Terminal and type this command:
`defaults read com.aone.keka ZipUsingAES`

**Comment by gingerbeardman** [comment]
This is because of sandboxing. 

1. Make sure you are replacing the prefs at correct sandbox location.
2. When I have had to do this, I have to open the settings plist itself in PListEdit Pro and copy and paste the contents from one plist to the other. So I guess there is some way the OS recognises if the prefs file was created by the app (I have not looked into this).

**Comment by aonez** [comment]
You're both right. In theory at the first launch Keka should migrate the preferences in the non-sandboxed plist. I'll check that one.

**Comment by aonez** [comment]
@built2order this should be fixed in the latests 1.2.0 development builds. I'm closing this one in favor of #15. Let me know there if you test that it works for you (I did).
