### ISSUE TITLE
List of recent passwords

### ISSUE THREAD

**Issue by Holger-Issle** [aonez/Keka#468]
Hi, 
how about a list of (zip) passwords to re-use them easily in the password entry box as a dropdown list? Ihr even auto-try known passwords for decompression, to make it easier to decompress different files over time with the same password?
Thanks for consideration,
Holger

**Comment by aonez** [comment]
> how about a list of (zip) passwords to re-use them easily in the password entry box as a dropdown list

I'm adding this idea as a possible feature in #26

> auto-try known passwords for decompression, to make it easier to decompress different files over time with the same password

The latest beta tries the latest used password, as long as Keka is open #108. But I'm adding your idea as well in #26, since the already developed retry functionality can be modified to use a list of saved passwords.

Thanks @Holger-Issle! Closing this one in favor of #26 :)
