### ISSUE TITLE
Keka keeps asking where to unpack, even with "next to original" set

### ISSUE THREAD

**Issue by Pomax** [aonez/Keka#564]
**Configuration**
Keka version: 1.1.29
macOS version: 1.13 high sierra

**Describe the bug**
I have keka set to extract "next to original", not "ask each time", but it keeps asking me where to unpack:

<img width="743" alt="Screen Shot 2020-05-30 at 8 42 34 PM" src="https://user-images.githubusercontent.com/177243/83343994-3844c500-a2b6-11ea-8ea5-116d572c8008.png">

**Comment by aonez** [comment]
@Pomax for this option to work Keka needs file access on the folder the source file is in. In this case, if you give Keka file access to your Documents folder (or your user folder) the option will work as expected.

This is due to sandbox limitations. More info [here](https://github.com/aonez/Keka/wiki/Sandbox#disk-access).

**Comment by Pomax** [comment]
I see. Thank you.
