### ISSUE TITLE
Changed mail in AppStore

### ISSUE THREAD

**Issue by tomov40** [aonez/Keka#583]
Hi guys, I have been buy this app, two year ago (or maybe more), and after that I change my primary e-mail on Apple app store account. In two week ago I reinstall my Macbook and now, wen I try to download Keka the appstore want to take money for me :)

**Comment by aonez** [comment]
Hi @tomov40. I really can't do nothing about this, you should contact Apple directly. Anyway, can you let me know the new email address at info@keka.io?

**Comment by tomov40** [comment]
Hi, this is the new e-mail. (tomov40@gmail.com), the old one was
miro@stantek.com

**Comment by aonez** [comment]
Probably you've created a new account instead of changing the old account primary mail address so the new account does not have any of your prior purchases. For anyone reading this, change the old account primary address and keep using that account. You may need to change the new account email before using it in the old account.
