### ISSUE TITLE
some issue with sleep.

### ISSUE THREAD

**Issue by Hardcore-fs** [aonez/Keka#602]
**Configuration**
Keka version: [11.30]
macOS version: [10.13.6]

**Describe the bug**
Take a 250 gb single file
run it thru 7ip set to "cd" so it splits it up.

Seems to crash around file 131, maybe related to sleep & wakeup, functions, since it is like a 6 hour run.......

**Comment by aonez** [comment]
@Hardcore-fs when you say crash, you mean that Keka crashed? Or the compression process failed? If it's a crash, please go to Console.app -> Crash reports and attach the log file here.

Keka prevents the Mac going to sleep automatically. Anyway if you manually go to sleep the process should not crash.

If this is not a crash but a failed process, is it possible that you re-run the process with [a debug session](https://github.com/aonez/Keka/wiki/Report-an-issue) enabled? Also having the Console.app opened and filtered with "Keka" may help since there may appear some macOS messages.

Thanks!

**Comment by Hardcore-fs** [comment]
I just updated the os.....
now it does not do it........
but it seemed to be related to starting a big compression & split,  entering sleep mode, then coming out of sleep mode, while still compressing in the background

**Comment by aonez** [comment]
Thanks for the followup @Hardcore-fs. I've tried to reproduce this with no luck. Please reopen if it happens again.
