### ISSUE TITLE
[BUG] Only part of the notification sound would play if the app closes too fast

### ISSUE THREAD

**Issue by Ranoiaetep** [aonez/Keka#653]
### Configuration
- Keka version: [e.g. 1.1.30 (3477)]
- macOS version: [e.g. 10.15.7 (19H2)]

### Describe the bug
The notification sound would prematurely stop if you have chosen not "Enable Notification Center Integration", "Close Keka when no windows are open",  and "Play sound after Compression/Extraction".

I believe it is because the app closes too fast, and the sound can't be fully played through.

### Expected behavior
Either close the app, and still have the entire sound played, or close the app after the sound has been entirely played.

### Additional context
Is it possible to change how long the notification banner would show? The reason I turned that off is because the duration feels a bit too long for me.

**Comment by aonez** [comment]
Thanks a lot for the feedback!

The sound issue is fixed in 1.2.0 versions. You can check that now in
https://beta.keka.io

About the time of the notification... as far as I know is not possible to
change it. You can see all the configuration in the  System Preferences -
Notifications. Maybe there’s an obscure way to change it, will investigate
it later.
