### ISSUE TITLE
No Love panel in WEB version

### ISSUE THREAD

**Issue by Marc66** [aonez/Keka#703]
### Configuration
- Keka version: 1.2.4
- macOS version: 10.13.6

### Describe the bug
Missing "Love" section in preferences

### To Reproduce
1. Go to Preferences
2. Look at available options
3. You can see General, Compression, Extraction, File Access, Performance, Finder Extension
4. But cannot see "Love"

### Expected behavior
There should be an additional option/tab after Finder Extension

### Screenshots
<img width="656" alt="Screenshot" src="https://user-images.githubusercontent.com/11850067/100394306-f1554380-303c-11eb-974a-8f5610b70147.png">

**Comment by aonez** [comment]
Thanks for the feedback @Marc66! The "Love" panel only appear on MAS (Mac App Store) version because the tips are In-App purchases and they will not work in the WEB version. Maybe in the future I'll add some donation buttons for the WEB version, but I don't see the need really.

If you want I can send you a code to redeem Keka from the MAS and check it there.
