### ISSUE TITLE
Use plzip instead of lzip

### ISSUE THREAD

**Issue by aonez** [aonez/Keka#75]
A continuation of #68.
For better speed compression and extraction, use multithreaded plzip instead of lzip.

- [ ] ~Binary must pause when asked~
- [x] Percentage progress must update

Since version 1.1.0-beta.3r2194, you can enable plzip:

```bash
defaults write com.aone.Keka UseMultithreadLzip <true|false>
```

**Comment by MaxPower85** [comment]
It doesn't seem like Keka is using plzip even with `defaults write com.aone.Keka UseMultithreadLzip true`

Even after restarting Keka... for .lz format it seems that only lzip is used... Activity Monitor shows kekalzip using a single thread... both when compressing a single file or multiple files...

I've tested plzip in Terminal and even with it's default settings it used multithreading and it was significantly faster than lzip Keka uses... it was also faster for decompressing .lz archives.

BTW... the progress bar in Keka isn't moving when you compress a single file to .lz format... it moves only when compressing multiple files.

I tried to open the Resources folder and to rename kekaplzip to kekalzip, to see if Keka would use it... and it seems to be working really well... after renaming it, Keka uses multithreading for .lz format... also, the progress bar for single files also seems to be working fine when plzip is used and it seems to be more accurate that the progress bar for multiple files.

So... just use plzip instead of lzip... and see if you can make the progress bar have the same behavior for multiple files too as it does for single files, since the progress bar seems to be working fine for single files when plzip is used.

**Comment by aonez** [comment]
> Even after restarting Keka... for .lz format it seems that only lzip is used... Activity Monitor shows kekalzip using a single thread... both when compressing a single file or multiple files...

I don't know why this is happening. It works on debug.

**Comment by aonez** [comment]
Really strange thing, the key seems to be deleted:

```sh
aONe-Mini:~ aone$ defaults read com.aone.Keka UseMultithreadLzip
2018-03-22 11:05:38.178 defaults[66713:671214] 
The domain/default pair of (com.aone.Keka, UseMultithreadLzip) does not exist
```

**Comment by aonez** [comment]
> BTW... the progress bar in Keka isn't moving when you compress a single file to .lz format... it moves only when compressing multiple files.

Fixed that for next revision.

**Comment by aonez** [comment]
Using `PLZIP` by default in next revision 1.1.9. You can still use `LZIP` setting [UseMultithreadLzip](https://github.com/aonez/Keka/wiki/Hidden-configuration#compression-and-extraction) to `FALSE`.
