### ISSUE TITLE
Button "Done" and "X" is not symmetrical to field

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#753]
### Configuration
- Keka version: 1.2.7 (4394)
- macOS version: 11.1 (20C69)

<img width="938" alt="104503969-13e9ee80-55e2-11eb-8450-ed4543b66181" src="https://user-images.githubusercontent.com/62497891/104511768-83b1a680-55ed-11eb-804c-8e777c9df525.png">

**Comment by aonez** [comment]
Never saw that one because I still work in @1x (no retina). And as you can see there is not possible to vertically align it perfectly because that `NSPopUpButton` object measures 19 (odd). So there's an inevitable extra pixel that decided to go in the bottom part:

![Screenshot 2021-01-18 at 12 47 40](https://user-images.githubusercontent.com/480163/104911780-af38e600-598b-11eb-81b1-0c6058eb9912.png)

But it measures 38 in @2x (retina) so there must be properly centered indeed:

![Screenshot 2021-01-18 at 12 54 22](https://user-images.githubusercontent.com/480163/104912300-62a1da80-598c-11eb-9751-4c6d6622765a.png)

**Comment by Oleg-Chashko** [comment]
Sooner or later, you'll have to, update your computer and macOS. Otherwise, you will not see all the problems. Which users will have. But you have to keep up with the times.

**Comment by aonez** [comment]
Not all people work on latest OS or retina and my environment must fit my working requirements. Right now I need to test Keka from 10.10 to 11.0, with and without retina. Not only 11.0 with retina.

**Comment by Oleg-Chashko** [comment]
> Not all people work on latest OS or retina and my environment must fit my working requirements. Right now I need to test Keka from 10.10 to 11.0, with and without retina. Not only 11.0 with retina.

I didn't offer to sell my old computer. But sooner or later you will have to buy a computer on the CPU m1, m2, etc.

**Comment by aonez** [comment]
Back to the main topic `center vertically` constraint condition does not work properly for @1x and @2x in this case and that's why I've used constants. I need to figure out how to accomplish the current behaviour in @1x and proper center in @2x together.

**Comment by Oleg-Chashko** [comment]
You already managed to fix a similar problem in this topic:
UI: Button "OK" and "X" is not symmetrical to the password input field. #708
Maybe this solution will work here too?

**Comment by aonez** [comment]
Sadly is not the same, #708 was caused by the changes in Big Sur UI so I simply needed to change and apply custom values to the constraint when running in Big Sur. In this case the issue is @1x vs @2x density, no OS dependant.

**Comment by aonez** [comment]
I did fixed this one in 1.2.8, was an overkill fix but will be useful for future @1 vs @2 (retina) issues. Thanks @Oleg-Chashko!
