### ISSUE TITLE
[BUG] The latest version is not capable of Mavericks 10.9.5

### ISSUE THREAD

**Issue by IORose** [aonez/Keka#761]
### Configuration
- Keka version: [1.2.7]
- macOS version: [OS X 10.9.5 (13F1911)]

### Bug Description
Unable to run the latest version on OS X Mavericks 10.9.5, even if it is "supported", according to the description on official website: 

![image](https://user-images.githubusercontent.com/70447619/104819355-ef8a4e00-583d-11eb-9b58-56f189c8732b.png)

Though, legacy 1.1.30 version runs perfectly, while the newest don't.

### To Reproduce
1. Download the latest version of Keka and try to run it on Mavericks 10.9.5. 

### Expected behavior
1. Keka launches without any compatibility issues.

### Screenshots
![image](https://user-images.githubusercontent.com/70447619/104819273-7be84100-583d-11eb-82da-67d7145aadf1.png)
![image](https://user-images.githubusercontent.com/70447619/104819283-8c98b700-583d-11eb-98c5-dcfd23bc45d2.png)

**Comment by aonez** [comment]
Thanks a lot for the tip @IORose! Added the version 1.1.30 to the legacy section but forgot to change the minimum required to 10.10 in the website... fixed now!

It was sad, as always, to remove support from a legacy OS but 10.9 was becoming extremely time consuming to support with the new additions.

Also updated the helper to 1.1.1 to support 10.9 again  because 1.1.0 was erroneously set to minimum 10.10.

Just out of curiosity, are you using an old Mac? I recently got back a second hand black Macbook from 2007, replaced the HDD with an SSD and it was awesome to see the crispness of 10.6 again.

**Comment by IORose** [comment]
> Just out of curiosity, are you using an old Mac?

Hello. No, I'm using my PC with Mac OS X Mavericks 10.9.5 Installed

i5 2400
16GB DDR3
NVidia GTX 650
OpenCore 0.6.4

I've just got bored with the new versions of macOS and wanted to "go back" to old versions for some time.

**Comment by aonez** [comment]
Nice! I did started Keka in some rebranded MSI laptop using Chameleon, OpenCore is so advanced. I'm curious how the M ARM processors will be handled in the scene. Closing this one but feel free to comment whatever.
