### ISSUE TITLE
In the "Performance" section, please move the checkboxes to the left

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#765]
In the "Performance" section, please move the checkboxes to the left. To match the design of other sections of your application.

**Currently**
<img width="975" alt="Screenshot 2021-01-21 at 15 54 01" src="https://user-images.githubusercontent.com/62497891/105370109-8753b780-5c03-11eb-935f-00ef432f5ae9.png">

**Currently in other sections of the application**
<img width="641" alt="Screenshot 2021-01-21 at 16 01 14" src="https://user-images.githubusercontent.com/62497891/105370282-b79b5600-5c03-11eb-90fe-aee267ebe3e7.png">
<img width="641" alt="Screenshot 2021-01-21 at 16 00 33" src="https://user-images.githubusercontent.com/62497891/105370296-bc600a00-5c03-11eb-8aef-32733896f310.png">

**It is desirable to do**
<img width="754" alt="Screenshot 2021-01-21 at 16 16 19" src="https://user-images.githubusercontent.com/62497891/105371387-dea65780-5c04-11eb-9c29-875c74435613.png">

**Comment by aonez** [comment]
The options in the Performance pane are "nested", that's why they're tabbed.

Take "Queue operations" as the title of the section, it has then the tabbed description and tabbed options. At this moment there is only an option for section but it may change in the future.

But I see your point, because in other panes there're no "titles" and therefore the options are no tabbed. Maybe a full redesign should be done for 1.3.0 -> #768
