### ISSUE TITLE
Use p7zip 17.03 fork

### ISSUE THREAD

**Issue by MaxPower85** [aonez/Keka#813]
I've noticed that Homebrew lists this version of 7zip https://github.com/jinfeihan57/p7zip

https://formulae.brew.sh/formula/p7zip

It adds support for some additional compression formats to be used for 7z and zip archives.

(BTW... if someone downloads it from the releases page, download the source and compile it yourself... the precompiled macOS binaries that they have there are showing some error on Sierra when you type "7z i" to see the supported formats, which does not seem to happened when you compile it yourself on Sierra).

To try different compression formats for .zip, you can use a command like this
`7za a -tzip -m0=deflate:x=9:mt=8 your_folder.zip your_folder`

Just change the "deflate" part to something else... formats that it allows for .zip are "deflate", "deflate64", "ppmd", "xz", "lzma", "bzip2" and "zstd". Using "deflate" compression is default for .zip. 

I think it would be good to add a drop-down box in Keka to choose between those compression formats for .zip, but just write that it's recommended to keep it on "deflate" for compatibility with more archivers.

For 7z format
`7za a -t7z -m0=lzma2:x=9:mt=8 your_folder.7z your_folder`

You can change the "lzma2" part to something else... formats that it allows for .7z are "deflate", "deflate64", "ppmd", "lzma", "lzma2", "flzma2", "bzip2", "brotli", "lz4", "lz5" and "zstd". Using "lzma2" compression is default for .7z.

**Comment by aonez** [comment]
I'm checking that fork of p7zip since it started. I'm not sure about using it since it's not following 7-Zip but adding security fixes (already used in 16.02 revisions in Debian and Keka) and some other formats (like ZSTD and BROTLI) which Keka already supports. I don't say this is bad but not sure Keka needs this.

What I would like is 19.00 or 21.00 to be ported, not a 16.02 modified fork. But obviously this is a lot of work.

Will build and check anyway, maybe one of those changes translate into some improvement while used in Keka:

- **17.02** supports Fast lzma2 1.0.1 compression method
- **17.03** use system local to select OEM code
- **17.03** add Lzfse to dmg

**Comment by aonez** [comment]
This will be probably it: https://sourceforge.net/p/sevenzip/discussion/45797/thread/cec5e63147

**Comment by aonez** [comment]
@MaxPower85 already published a build using new `7zz` (7-Zip 21.02):

https://github.com/aonez/Keka/releases/tag/v1.2.15-dev.4573
