### ISSUE TITLE
I would like to get a refund 

### ISSUE THREAD

**Issue by nckrtl** [aonez/Keka#9]
I would like to get a refund, as i purchased a version of Keka but it doens't work as expected. I wanted to encrypt files with AES 256 but the option doesn't seem to be there. How can i get a refund?

**Comment by aonez** [comment]
Sorry to hear that. Using 7z, just setting a password encrypts the file in AES256, there's no other option than AES256. For Zip, by default is not AES256 since it is not compatible in macOS by default, but if you want you can activate it following this simple steps:
http://trac.kekaosx.com/wiki/AES256

So in short Keka encrypts in AES256 in 7z and in Zip if you activate it (loosing compatibility).

Anyway, if you still want a refund I cannot provide it. Apple must, here you can report your issue:
https://support.apple.com/en-us/HT204084
