### ISSUE TITLE
Some icons from v1.1 not showing

### ISSUE THREAD

**Issue by hashb** [aonez/Keka#92]
This bug is in prerelease (beta 5) of keka on mac os High sierra. 
<img width="882" alt="screen shot 2017-10-25 at 4 15 00 pm" src="https://user-images.githubusercontent.com/3821043/32026091-ff80baa0-b99f-11e7-8314-9fc4ba10c884.png">

formats:
- `*.tar.xz`
- `*.rar`
- `*.7z`

**Comment by aonez** [comment]
I also found this on some machines, but did not found a proper way to reproduce it or to fix it via code.

This also happens in 10.11.6 El Capitan. Also found the same issue with other apps, not just Keka, not just compression ones. Seems to be some kind of issue with the code that sets the handler:

```objc
LSSetDefaultRoleHandlerForContentType((CFStringRef)type, kLSRolesViewer, (CFStringRef)handler);
```

The application becomes the default one, but LS does not update the icon consistently.

Just found a workaround, let me know if it works for you:

![untitled mov](https://user-images.githubusercontent.com/480163/32041952-50a9c0f2-ba36-11e7-9ab1-226874266bf6.gif)

**Comment by aonez** [comment]
By the way received the first tip about this issue on beta 3, from [deadman36g](http://forum.kekaosx.com/memberlist.php?mode=viewprofile&u=897):

http://forum.kekaosx.com/viewtopic.php?f=6&t=2135

**Comment by Jax0rz** [comment]
I think the problem is caused by some changes in beta5,the beta4 is ok.

**Comment by aonez** [comment]
@Jax0rz if you delete beta 5 and use beta 4 instead, there’s no issue? Deleting beta 4 and using beta 5 again causes the issue?

**Comment by Jax0rz** [comment]
@aonez ,I think this bug is relative with some changes in beta5

> 
![capto_capture 2017-12-15_20-28-09_](https://user-images.githubusercontent.com/7557357/34043108-8c4afaa6-e1da-11e7-934d-7e4c813bae77.png)

I made a compare with beta4 vs beta5

beta4:
<img width="1440" alt="screen shot 2017-12-15 at 20 53 43" src="https://user-images.githubusercontent.com/7557357/34043140-a8b91498-e1da-11e7-97ff-7b1f03fd1059.png">

beta5:
<img width="1440" alt="screen shot 2017-12-15 at 20 54 42" src="https://user-images.githubusercontent.com/7557357/34043149-b489b386-e1da-11e7-9795-175c83168e25.png">

**Comment by tenwx** [comment]
I also encountered this problem, concerned about this issue.

**Comment by aonez** [comment]
@Jax0rz the removed icons where not used anymore. Here the thing is really strange, because with the same build on the same machine, I've got all the icons to show or some missing.

@tenwx I must fix this before final release for sure.

**Comment by aonez** [comment]
Can anyone confirm this is not happening on 1.1.0-beta.8? I can't get this error no more. Seems the optimisation done on the icons helped here.

**Comment by tenwx** [comment]
@aonez It still not be solved. :(
![image](https://user-images.githubusercontent.com/3733304/38226883-490725b8-372e-11e8-8cd4-3973d5129b9f.png)

**Comment by aonez** [comment]
So contacted with Apple and told me to fill a [bug report](https://bugreport.apple.com), that's what I'm gonna do next. You can use the trick I've shared in the animation, pretty quick, or do some of the cache cleaning found [here](https://gist.github.com/fabiofl/5873100), that also work but clear ALL the icons cache, not just the 2-3 formats missing.

**Comment by aonez** [comment]
Any of you replicated this issue on 10.13.5 beta 2?

**Comment by aonez** [comment]
Forget the message above, I’m fixing this within the Info.plist. Hopefully in a few hours I’ll upload a fixed version.

**Comment by aonez** [comment]
@tenwx, @hashb and @Jax0rz, could you test this build? [Keka-1.1.0-r2571.zip](https://github.com/aonez/Keka/files/1927922/Keka-1.1.0-r2571.zip)

I'm getting mostly good results on all tests. Just some random 32px zipped white representations of 7z files and some plain white too on bigger sizes, but the preview looks ok.

You may need to restart the Finder/Dock or just make a complete machine restart.

```sh
killall Finder; killall Dock
```

Also, note that the problem was a file type identification, nothing to do with the icon. Asure that the "Kind"  column looks similar as this for all the files tested:

![screen shot 2018-04-19 at 13 46 01](https://user-images.githubusercontent.com/480163/38989716-1ca3d03c-43d8-11e8-86d9-c9648d3af9f9.png)

If this build still has some problems, I may get rid of the [UTI](https://en.wikipedia.org/wiki/Uniform_Type_Identifier)s, since those seem to be the cause of the non correct identification, and where non present on 1.0.x versions with the older icons.

**Comment by aonez** [comment]
Must be resolved on [v1.1.0-rc.1](https://github.com/aonez/Keka/tree/v1.1.0-rc.1).

**Comment by gingerbeardman** [comment]
What were the plist changes?

**Comment by aonez** [comment]
@gingerbeardman it seems that if you define the `CFBundleDocumentTypes` array with `LSItemContentTypes` and/or `CFBundleTypeMIMETypes`, the OS may fail to associate only by file extension. So in a machine with no MIME or UTI defined for a 7Z file (for example), it will not be properly associated.

To solve this issue you must define `UTImportedTypeDeclarations`, and specify there the MIME and/or UTI for those files that are not defined by default in the OS.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<dict>
		<key>UTTypeIdentifier</key>
		<string>org.7-zip.7-zip-archive</string>
		<key>UTTypeIconFile</key>
		<string>7z</string>
		<key>UTTypeConformsTo</key>
		<array>
			<string>public.data</string>
			<string>public.archive</string>
		</array>
		<key>UTTypeDescription</key>
		<string>7Z Archive</string>
		<key>UTTypeTagSpecification</key>
		<dict>
			<key>public.mime-type</key>
			<array>
				<string>application/x-7z-compressed</string>
			</array>
			<key>public.filename-extension</key>
			<array>
				<string>7z</string>
			</array>
		</dict>
	</dict>
</array>
</plist>
```
